services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres
    environment:
        POSTGRES_USER: "webapp:${DB_USER}"
        POSTGRES_PASSWORD: "webapp:${DB_PASSWORD}"
        POSTGRES_DB: "webapp:${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
  pgdata: {}
