services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: iot-gateway
    restart: always
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=false
      - TS_HOSTNAME=iot-gateway
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - iot_net

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/pwfile:/mosquitto/config/pwfile
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
      - tailscale
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    dns:
      - 100.100.100.100
    networks:
      - iot_net

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # TODO: I exposed this for local development
    networks:
      - iot_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge

volumes:
  mosquitto_data: {}
  mosquitto_log: {}
  grafana_data: {}
  tailscale_data: {}
  postgres_data: {}
