"""add weather_current table

Revision ID: 1345d498e1b1
Revises: 04cddab8405c
Create Date: 2026-08-23 18:58:32.313312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1345d498e1b1'
down_revision: Union[str, Sequence[str], None] = '04cddab8405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_current',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time')
    )
    op.execute("SELECT create_hypertable('weather_current', 'time', if_not_exists => TRUE);")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_current')
    # ### end Alembic commands ###