"""add meteoswiss forecast table

Revision ID: 1e739c4f2e47
Revises: 1345d498e1b1
Create Date: 2026-09-01 07:13:16.315735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1e739c4f2e47'
down_revision: Union[str, Sequence[str], None] = '1345d498e1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteoswiss_forecast',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter', sa.Text(), nullable=False),
    sa.Column('station', sa.Text(), nullable=False),
    sa.Column('abbreviation', sa.Text(), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('point_type_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('fetch_runtime', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('time', 'parameter', 'station')
    )
    op.execute("SELECT create_hypertable('meteoswiss_forecast', 'time', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meteoswiss_forecast')
    # ### end Alembic commands ###