"""initial migration

Revision ID: 63b5248db74e
Revises: 
Create Date: 2026-01-16 23:27:57.100178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b5248db74e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distributor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('distributor', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['distributor'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reader', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('sensor_0_name', sa.Text(), nullable=True),
    sa.Column('sensor_0_value', sa.Float(), nullable=True),
    sa.Column('sensor_1_name', sa.Text(), nullable=True),
    sa.Column('sensor_1_value', sa.Float(), nullable=True),
    sa.Column('sensor_2_name', sa.Text(), nullable=True),
    sa.Column('sensor_2_value', sa.Float(), nullable=True),
    sa.Column('sensor_3_name', sa.Text(), nullable=True),
    sa.Column('sensor_3_value', sa.Float(), nullable=True),
    sa.Column('sensor_4_name', sa.Text(), nullable=True),
    sa.Column('sensor_4_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reader'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###

    # Manually added to create hypertable
    op.execute("SELECT create_hypertable('sensor_readings', 'timestamp', if_not_exists => TRUE);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('components')
    op.drop_table('readers')
    op.drop_table('locations')
    op.drop_table('distributors')
    # ### end Alembic commands ###
