"""normalized sensor_readings

Revision ID: 75dc45a8afb7
Revises: 63b5248db74e
Create Date: 2026-01-23 21:22:45.537844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dc45a8afb7'
down_revision: Union[str, Sequence[str], None] = '63b5248db74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('topic', sa.Text(), nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_type', sa.Text(), nullable=True))
    op.add_column('sensor_readings', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('unit', sa.Text(), nullable=True))
    op.drop_column('sensor_readings', 'sensor_2_name')
    op.drop_column('sensor_readings', 'sensor_3_value')
    op.drop_column('sensor_readings', 'sensor_3_name')
    op.drop_column('sensor_readings', 'sensor_1_name')
    op.drop_column('sensor_readings', 'sensor_2_value')
    op.drop_column('sensor_readings', 'sensor_1_value')
    op.drop_column('sensor_readings', 'sensor_0_value')
    op.drop_column('sensor_readings', 'sensor_4_name')
    op.drop_column('sensor_readings', 'sensor_4_value')
    op.drop_column('sensor_readings', 'sensor_0_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('sensor_0_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_4_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_4_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_0_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_1_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_2_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_1_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_3_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_3_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensor_readings', sa.Column('sensor_2_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sensor_readings', 'unit')
    op.drop_column('sensor_readings', 'value')
    op.drop_column('sensor_readings', 'sensor_type')
    op.drop_column('sensor_readings', 'topic')
    # ### end Alembic commands ###
