"""add gemini climate advice table

Revision ID: b51e815afd73
Revises: 1e739c4f2e47
Create Date: 2026-09-03 07:02:12.289102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b51e815afd73'
down_revision: Union[str, Sequence[str], None] = '1e739c4f2e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_advice',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station', sa.Text(), nullable=False),
    sa.Column('predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'station')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climate_advice')
    # ### end Alembic commands ###
